### ISSUE TITLE
Multiple routes with different check

### ISSUE THREAD

**Issue by olegstepura** [MacPaw/symfony-health-check-bundle#20]
Hi!

Is it possible to have multiple routes configured to have different checks in different routes?
Use case is kubernetes liveness and readiness probes:
- liveness probe is the one we would like to have running pretty often (each 10 sec) and having doctrine check in it is too much.
- but readiness probe can be done using longer interval (once per minute) and include doctrine check to make sure everything is setup correctly

Thanks!

**Comment by Yozhef** [comment]
Thank you, it sounds really cool - so we will turn it into a feature request and discuss with the team regarding the implementation but currently, there is no such implementation

**Comment by Yozhef** [comment]
@olegstepura sorry for the long answer a little busy - we are thinking of running an extra ping route and extra config on it - where you can just specify another set of checkers you need - will this solution cover your needs?

**Comment by olegstepura** [comment]
Yeah, I think it will.

**Comment by Yozhef** [comment]
Result: 
We create a new endpoint `/ping` then people can configure another set of checks.

**Comment by Yozhef** [comment]
https://github.com/MacPaw/symfony-health-check-bundle/pull/48

**Comment by olegstepura** [comment]
Cool, thanks! I think it's worth documenting new endpoint type 😉 Did you release a new version?

**Comment by Yozhef** [comment]
By the end of this week, there will be a new release of 2.0, it will be a bit with new dependencies - but I will describe in the Upgrade Doc all the changes

**Comment by Yozhef** [comment]
@olegstepura done https://github.com/MacPaw/symfony-health-check-bundle/releases/tag/v1.0.1 - now we are waiting merge Symfony recipes, but you can upgrade manually by documentation - https://github.com/MacPaw/symfony-health-check-bundle/blob/develop/UPGRADE-1.0.md

**Comment by olegstepura** [comment]
Super, thanks!

**Comment by Yozhef** [comment]
Thank you for your request, if you have any questions we will be happy to answer - sorry for the long implementation
