### ISSUE TITLE
Doctrine deprecated ping()

### ISSUE THREAD

**Issue by optior** [MacPaw/symfony-health-check-bundle#36]
In this https://github.com/doctrine/dbal/pull/4119 doctrine deprecated the ping method and is removed in version 3. I think it would be a good idea to reflect this in https://github.com/MacPaw/symfony-health-check-bundle/blob/develop/src/Check/DoctrineCheck.php. Currently the doctrine check return doctrine => false if you're using doctrine 3.

**Comment by Yozhef** [comment]
@optior Thank you for the notification, we will update in the near future

**Comment by Yozhef** [comment]
@optior we are waiting for stability from the codecov service and we are releasing it.

**Comment by Yozhef** [comment]
@optior done new tag 0.7.0
