### ISSUE TITLE
Add parameter Custom Error Json Response errorResponseCode: int  (default: 200);

### ISSUE THREAD

**Issue by Yozhef** [MacPaw/symfony-health-check-bundle#45]
errorResponseCode: int  (default: 200);
If one of check is failed your Json Response Code change to your custom response code.

**Comment by oparshyna** [comment]
Hi, it would be great to have such possibility to add custom response code. In some cases if any of checks fails means, that the whole service doesn't work.  And error response code could be very useful for such cases

**Comment by guedressel** [comment]
This fork implements this behaviour:

https://github.com/jpvdw86/symfony-health-check-bundle

**Comment by Yozhef** [comment]
@guedressel  Soon it will be implemented in our country as well, with greater abstraction thanks to @oparshyna

**Comment by Yozhef** [comment]
@guedressel sorry for the long processing of the request, we are preparing to release these changes that will cover this issue: https://github.com/MacPaw/symfony-health-check-bundle/pull/63

**Comment by Yozhef** [comment]
Many thanks to @oparshyna  for the work done)
