### ISSUE TITLE
Exclude successful responses from logs

### ISSUE THREAD

**Issue by lampelk** [MacPaw/symfony-health-check-bundle#62]
Is there any way to remove successful requests from the logs? My log files are flooded with requests (`level:200`/`channel:request`) in among all normal routing requests (which I want to retain), I can get around the log analysis by using filters but the log files are huge and it seems counterintuitive to have them both. Any advice would be most welcome.

**Comment by Yozhef** [comment]
In the new release, you will be able to change the http response code and ignore it in the logs.
https://github.com/MacPaw/symfony-health-check-bundle/pull/63/files
