### ISSUE TITLE
Release 1.03 is considered higher than 1.1.0

### ISSUE THREAD

**Issue by arielcostas-estelaria** [MacPaw/symfony-health-check-bundle#65]
**Describe the bug**
When installing the package via Composer, the latest version downloaded is `1.03`, being considered newer than `1.1.0`. I believe this is because version 1.03 is considered "1.3", and thus newer than 1.1.0.

**To Reproduce**
a. Install the bundle via Symfony Flex
b. Install the package directly
c. [Check on packagist](https://packagist.org/packages/macpaw/symfony-health-check-bundle) that 1.03 is sorted as newer than 1.1.0

**Expected behaviour**
Version 1.1.0 is installed

**Screenshots**
![image](https://github.com/MacPaw/symfony-health-check-bundle/assets/139213385/56dd6883-0403-4696-bf90-4db259d4f0d5)

![image](https://github.com/MacPaw/symfony-health-check-bundle/assets/139213385/de151183-b138-4797-b243-5aff2b8d6815)

**Proposed solution**
Republish the latest release as `1.4`, which would be newer than `1.03`.  Since the changes in `1.1.0` are not breaking, updating the minor version would no harm, while ensure both users of `1.03`and `1.1.0` know of the update.

**Comment by Yozhef** [comment]
@arielcostas-estelaria  thank you very much for signaling the problem - I deleted the problematic tag and created a new [1.4.0](https://github.com/MacPaw/symfony-health-check-bundle/releases/tag/v1.4.0)
